#![allow(unused_imports, reason = "generated golden test")]

// Generated by `cargo xtask generate-goldens`.
// From samples/FluidR3Mono_GM.sf2. Do not edit by hand.

use rustysynth_ext::SoundFont;
use std::fs::{self, File};
use std::path::PathBuf;

use crate::instrument_util;

#[test]
fn regions() {
    let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    path.pop();
    path.push("samples");
    path.push("FluidR3Mono_GM.sf2");
    let mut file = File::open(&path).unwrap();
    let sf = SoundFont::new(&mut file).unwrap();

    assert_eq!(sf.get_instruments().len(), 201);
    assert_eq!(
        sf.get_instruments()
            .iter()
            .map(|i| i.get_regions().len())
            .sum::<usize>(),
        1845
    );

    let data_path =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("data/fluidr3mono_instrument_regions.bin");
    let data = fs::read(&data_path).unwrap();
    assert_eq!(data.len(), 1845 * 50 * 8);

    let mut index = 0;
    for instrument in sf.get_instruments() {
        for region in instrument.get_regions() {
            let row = &data[index * 50 * 8..(index + 1) * 50 * 8];
            let values: [f64; 50] = std::array::from_fn(|i| {
                f64::from_le_bytes(row[i * 8..i * 8 + 8].try_into().unwrap())
            });
            instrument_util::check(region, &values);
            index += 1;
        }
    }
}
