#![allow(unused_imports)]

// Generated by `cargo xtask generate-goldens`.
// From samples/FluidR3Mono_GM.sf2. Do not edit by hand.

use rustysynth::SoundFont;
use std::fs::{self, File};
use std::path::PathBuf;

#[test]
fn soundfont_info() {
    let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    path.pop();
    path.push("samples");
    path.push("FluidR3Mono_GM.sf2");
    let mut file = File::open(&path).unwrap();
    let sf = SoundFont::new(&mut file).unwrap();

    let info = sf.get_info();

    assert_eq!(info.get_version().get_major(), 2);
    assert_eq!(info.get_version().get_minor(), 4);
    assert_eq!(info.get_target_sound_engine(), "MuseScore FluidSynth");
    assert_eq!(info.get_bank_name(), "FluidR3Mono_GM2-305.SF2");
    assert_eq!(info.get_rom_name(), "");
    assert_eq!(info.get_rom_version().get_major(), 0);
    assert_eq!(info.get_rom_version().get_minor(), 0);
    assert_eq!(info.get_creation_date(), "27th March 2016");
    assert_eq!(info.get_author(), "Frank Wen & Michael Cowgill - see License file for other details");
    assert_eq!(info.get_target_product(), "SBAWE32");
    assert_eq!(info.get_copyright(), "Frank Wen 2000-2002, Michael Cowgill 2014-16");
    assert_eq!(info.get_comments().len(), 85);
    assert_eq!(info.get_tools(), "Polyphone");

    assert_eq!(sf.get_wave_data().len(), 62097631);

    let mut sum: i32 = 0;
    for value in sf.get_wave_data().iter() {
        sum += *value as i32;
    }
    assert_eq!(sum, 417258584)
}
