#![allow(unused_imports, reason = "generated golden test")]

// Generated by `cargo xtask generate-goldens`.
// From samples/FluidR3Mono_GM.sf3. Do not edit by hand.

use rustysynth::SoundFont;
use std::fs::{self, File};
use std::path::PathBuf;

use crate::preset_util;

#[test]
fn regions() {
    let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    path.pop();
    path.push("samples");
    path.push("FluidR3Mono_GM.sf3");
    let mut file = File::open(&path).unwrap();
    let sf = SoundFont::new(&mut file).unwrap();

    assert_eq!(sf.get_presets().len(), 195);
    assert_eq!(
        sf.get_presets()
            .iter()
            .map(|p| p.get_regions().len())
            .sum::<usize>(),
        960
    );

    let data_path =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("data/fluidr3mono_sf3_preset_regions.bin");
    let data = fs::read(&data_path).unwrap();
    assert_eq!(data.len(), 960 * 39 * 8);

    let mut index = 0;
    for preset in sf.get_presets() {
        for region in preset.get_regions() {
            let row = &data[index * 39 * 8..(index + 1) * 39 * 8];
            let values: [f64; 39] = std::array::from_fn(|i| {
                f64::from_le_bytes(row[i * 8..i * 8 + 8].try_into().unwrap())
            });
            preset_util::check(region, &values);
            index += 1;
        }
    }
}
