#![allow(unused_imports, reason = "generated golden test")]

// Generated by `cargo xtask generate-goldens`.
// From samples/TimGM6mb.sf2. Do not edit by hand.

use rustysynth::SoundFont;
use std::fs::{self, File};
use std::path::PathBuf;

use crate::sample_util;

#[test]
fn samples() {
    let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    path.pop();
    path.push("samples");
    path.push("TimGM6mb.sf2");
    let mut file = File::open(&path).unwrap();
    let sf = SoundFont::new(&mut file).unwrap();

    assert_eq!(sf.get_sample_headers().len(), 520);

    let data_path =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("data/timgm6mb_sample_headers.bin");
    let data = fs::read(&data_path).unwrap();
    assert_eq!(data.len(), 520 * 7 * 4);

    for (index, sample) in sf.get_sample_headers().iter().enumerate() {
        let row = &data[index * 7 * 4..(index + 1) * 7 * 4];
        let values: [i32; 7] =
            std::array::from_fn(|i| i32::from_le_bytes(row[i * 4..i * 4 + 4].try_into().unwrap()));
        sample_util::check(sample, &values);
    }
}
